version: '3.5'
services:
  goofys:
    build: .
    privileged: true
    environment:
      AWS_ACCESS_KEY: 1234
      AWS_SECRET_KEY: 5678
    tty: true
    volumes: 
     - /mnt/s3/:/mnt/s3/:shared
